# Generated by Django 2.2.1 on 2019-06-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190624_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulacoes',
            name='aposentado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='simulacoes',
            name='apto',
            field=models.BooleanField(default=False),
        ),
    ]
